import { homedir } from 'node:os';
import nodePath from 'node:path';
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { copyTree } from './copy.js';
import { parseFrontmatter } from '../frontmatter.js';

// Codex CLI: there is no native "skill" folder concept like Claude Code's, so we
// (a) copy the full skill source under <base>/skills/<name>/ (scripts/assets), and
// (b) write a slash-prompt at <base>/prompts/<name>.md that loads it.
//
// base/installDir/envFile take an optional { home, cwd, path } so tests can assert
// the Windows layout from any OS (pass path: require('node:path').win32). Real
// callers pass nothing and get the live homedir()/cwd()/platform path module.
export const codex = {
  id: 'codex',

  base(scope, { home = homedir(), cwd = process.cwd(), path = nodePath } = {}) {
    return scope === 'project'
      ? path.join(cwd, '.codex')
      : path.join(home, '.codex');
  },

  installDir(scope, opts = {}) {
    const path = opts.path ?? nodePath;
    return path.join(this.base(scope, opts), 'skills');
  },

  envFile(scope, opts = {}) {
    const path = opts.path ?? nodePath;
    return scope === 'project'
      ? path.join(opts.cwd ?? process.cwd(), '.env')
      : path.join(this.base('user', opts), '.env');
  },

  commonPromptFile(scope, opts = {}) {
    const path = opts.path ?? nodePath;
    return scope === 'project'
      ? path.join(opts.cwd ?? process.cwd(), 'AGENTS.md')
      : path.join(this.base('user', opts), 'AGENTS.md');
  },

  write(skill, scope) {
    const dest = nodePath.join(this.installDir(scope), skill.folder);
    copyTree(skill.dir, dest);

    // Build a Codex prompt that points at the copied skill instructions.
    const raw = readFileSync(nodePath.join(skill.dir, 'SKILL.md'), 'utf8');
    const { body } = parseFrontmatter(raw);
    const promptsDir = nodePath.join(this.base(scope), 'prompts');
    mkdirSync(promptsDir, { recursive: true });
    const header =
      `<!-- generated by hfa from skill "${skill.name}" (${skill.type}) -->\n` +
      `Skill: ${skill.name}\nSource: ${dest}\n\n`;
    writeFileSync(nodePath.join(promptsDir, `${skill.folder}.md`), header + (body || ''));
    return dest;
  },
};
