import { homedir } from 'node:os';
import { join } from 'node:path';
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { copyTree } from './copy.js';
import { parseFrontmatter } from '../frontmatter.js';

// Codex CLI: there is no native "skill" folder concept like Claude Code's, so we
// (a) copy the full skill source under <base>/skills/<name>/ (scripts/assets), and
// (b) write a slash-prompt at <base>/prompts/<name>.md that loads it.
//
// NOTE: exact Codex paths/format should be confirmed against the installed Codex
// CLI version; the adapter abstraction is what's fixed, not these specifics.
export const codex = {
  id: 'codex',

  base(scope) {
    return scope === 'project'
      ? join(process.cwd(), '.codex')
      : join(homedir(), '.codex');
  },

  installDir(scope) {
    return join(this.base(scope), 'skills');
  },

  envFile(scope) {
    return scope === 'project'
      ? join(process.cwd(), '.env')
      : join(this.base('user'), '.env');
  },

  write(skill, scope) {
    const dest = join(this.installDir(scope), skill.folder);
    copyTree(skill.dir, dest);

    // Build a Codex prompt that points at the copied skill instructions.
    const raw = readFileSync(join(skill.dir, 'SKILL.md'), 'utf8');
    const { body } = parseFrontmatter(raw);
    const promptsDir = join(this.base(scope), 'prompts');
    mkdirSync(promptsDir, { recursive: true });
    const header =
      `<!-- generated by hfa from skill "${skill.name}" (${skill.type}) -->\n` +
      `Skill: ${skill.name}\nSource: ${dest}\n\n`;
    writeFileSync(join(promptsDir, `${skill.folder}.md`), header + (body || ''));
    return dest;
  },
};
