// Routing table: a consolidated, always-loaded list of every skill — its
// trigger phrases and where its SKILL.md lives — for injection into a runtime's
// common-prompt file (Claude Code CLAUDE.md, Codex/OpenClaw AGENTS.md). Agents
// see only name + description, so this advertises the whole toolbox up-front
// instead of relying on lazy discovery.
//
// Block is delimited by markers so it can be re-injected idempotently, the same
// pattern scripts/sync-preamble.js uses for the analyst-kit-core preamble/epilogue.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { getSkills } from './registry.js';

export const ROUTING_START =
  '<!-- analyst-kit:skills:start — generated by scripts/build-routing-table.js; do not edit by hand -->';
export const ROUTING_END = '<!-- analyst-kit:skills:end -->';
const ROUTING_RE = /<!-- analyst-kit:skills:start[\s\S]*?analyst-kit:skills:end -->/;

// Trigger phrases are wrapped in quotes. Prefer double quotes — so an apostrophe
// inside a phrase ("pull <manager>'s 13F", "what's the P/E") isn't mistaken for a
// delimiter — and fall back to single quotes only when a description uses them
// (those descriptions have no internal apostrophes). Curly variants included.
const DOUBLE_QUOTED = /[“”"]([^“”"]+)[“”"]/g;
const SINGLE_QUOTED = /[‘’']([^‘’']+)[‘’']/g;

// Pull trigger phrases out of a skill description. Triggers live after a
// "Triggers:" label; grab the quoted phrases and ignore any trailing prose.
// Falls back to the first sentence when a description has no quoted triggers.
export function extractTriggers(description = '', max = 6) {
  const i = description.search(/triggers:/i);
  const tail = i >= 0 ? description.slice(i + 'triggers:'.length) : description;
  let phrases = [...tail.matchAll(DOUBLE_QUOTED)].map((m) => m[1].trim()).filter(Boolean);
  if (!phrases.length) {
    phrases = [...tail.matchAll(SINGLE_QUOTED)].map((m) => m[1].trim()).filter(Boolean);
  }
  if (phrases.length) {
    const shown = phrases.slice(0, max).map((p) => `"${p}"`).join(', ');
    return phrases.length > max ? `${shown}, …` : shown;
  }
  const head = (i >= 0 ? description.slice(0, i) : description).trim();
  return head.split(/(?<=[.!?])\s/)[0].trim() || description.trim();
}

// Order: workflows (entry points) first, then capabilities, then analyst-kit-core
// (the runtime) last; alphabetical within each group. Deterministic for --check.
function ordered(skills) {
  const rank = (s) => (s.name === 'analyst-kit-core' ? 2 : s.type === 'workflow' ? 0 : 1);
  return skills.slice().sort((a, b) => rank(a) - rank(b) || a.name.localeCompare(b.name));
}

function loadPath(skillsDir, folder) {
  return `${String(skillsDir).replace(/[\\/]+$/, '')}/${folder}/SKILL.md`;
}

// Build the routing-table block (markers included). `skillsDir` is substituted
// into the Load column — pass a runtime's real skills dir (e.g. ~/.claude/skills)
// or leave the default <skills-dir> token for documentation.
export function buildRoutingTable(
  skills = getSkills(),
  { skillsDir = '<skills-dir>', includeLoad = true } = {},
) {
  const rows = ordered(skills).map((s) => {
    const when = s.name === 'analyst-kit-core'
      ? `runtime (auto-installed): ${extractTriggers(s.description, 4)}`
      : extractTriggers(s.description);
    return includeLoad
      ? `| ${s.name} | ${when} | \`${loadPath(skillsDir, s.folder)}\` |`
      : `| ${s.name} | ${when} |`;
  });
  // Cowork skills are app-managed, so a filesystem Load column is meaningless there
  // (includeLoad: false drops it) — the table is then pure dispatch guidance.
  const header = includeLoad
    ? ['| Skill | Use when the user… | Load |', '|-------|--------------------|------|']
    : ['| Skill | Use when the user… |', '|-------|--------------------|'];
  return [
    ROUTING_START,
    '## Analyst Kit skills (routing table)',
    '',
    "When a request matches a skill's triggers, use that skill.",
    '',
    ...header,
    ...rows,
    ROUTING_END,
  ].join('\n');
}

// Idempotently write the routing block into a common-prompt file. Replaces an
// existing block between markers, else appends; creates the file (and parent
// dir) if missing. Returns true if the file changed.
export function injectRoutingTable(filePath, block) {
  const current = existsSync(filePath) ? readFileSync(filePath, 'utf8') : '';
  let next;
  if (ROUTING_RE.test(current)) {
    next = current.replace(ROUTING_RE, block);
  } else if (current.trim()) {
    next = `${current.trimEnd()}\n\n${block}\n`;
  } else {
    next = `${block}\n`;
  }
  if (next === current) return false;
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, next);
  return true;
}

// Check (no write) whether a file already holds exactly `block`.
export function routingTableInSync(filePath, block) {
  const current = existsSync(filePath) ? readFileSync(filePath, 'utf8') : '';
  const m = current.match(ROUTING_RE);
  return !!m && m[0] === block;
}

// Skill names currently listed in a file's routing block (first table column).
export function parseRoutingSkillNames(content) {
  const m = content.match(ROUTING_RE);
  if (!m) return new Set();
  const names = new Set();
  for (const line of m[0].split('\n')) {
    const cell = /^\|\s*([^|]+?)\s*\|/.exec(line);
    if (cell) names.add(cell[1].trim());
  }
  return names;
}

// Merge `addSkills` into a file's routing table (union by name) and inject, so
// repeated installs accumulate skills instead of overwriting the table. Rows are
// re-rendered from `allSkills`. Returns true if the file changed.
export function upsertRoutingTable(filePath, addSkills, { skillsDir = '<skills-dir>', allSkills = getSkills() } = {}) {
  const known = new Map(allSkills.map((s) => [s.name, s]));
  const names = new Set(addSkills.map((s) => s.name));
  const existing = existsSync(filePath) ? readFileSync(filePath, 'utf8') : '';
  for (const n of parseRoutingSkillNames(existing)) if (known.has(n)) names.add(n);
  const skills = allSkills.filter((s) => names.has(s.name));
  return injectRoutingTable(filePath, buildRoutingTable(skills, { skillsDir }));
}
